version: '3.3'
services:
  fsdb:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'fs-storage-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'